import unittest


class TestExceptions(unittest.TestCase):
    pass


if __name__ == '__main__':
    unittest.main()
